# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lanegui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 900))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.config_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.config_label.setFont(font)
        self.config_label.setAlignment(QtCore.Qt.AlignCenter)
        self.config_label.setObjectName("config_label")
        self.gridLayout_5.addWidget(self.config_label, 2, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.outputformat_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.outputformat_dropdown.setObjectName("outputformat_dropdown")
        self.outputformat_dropdown.addItem("")
        self.outputformat_dropdown.addItem("")
        self.outputformat_dropdown.addItem("")
        self.gridLayout_3.addWidget(self.outputformat_dropdown, 2, 1, 1, 1)
        self.framrate_label = QtWidgets.QLabel(self.centralwidget)
        self.framrate_label.setObjectName("framrate_label")
        self.gridLayout_3.addWidget(self.framrate_label, 1, 0, 1, 1)
        self.outputformat_label = QtWidgets.QLabel(self.centralwidget)
        self.outputformat_label.setObjectName("outputformat_label")
        self.gridLayout_3.addWidget(self.outputformat_label, 2, 0, 1, 1)
        self.play_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_button.setObjectName("play_button")
        self.gridLayout_3.addWidget(self.play_button, 3, 1, 1, 1)
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setObjectName("save_button")
        self.gridLayout_3.addWidget(self.save_button, 3, 0, 1, 1)
        self.framerate_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.framerate_dropdown.setObjectName("framerate_dropdown")
        self.framerate_dropdown.addItem("")
        self.framerate_dropdown.addItem("")
        self.framerate_dropdown.addItem("")
        self.framerate_dropdown.addItem("")
        self.framerate_dropdown.addItem("")
        self.gridLayout_3.addWidget(self.framerate_dropdown, 1, 1, 1, 1)
        self.displayannotation_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.displayannotation_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.displayannotation_checkbox.setObjectName("displayannotation_checkbox")
        self.gridLayout_3.addWidget(self.displayannotation_checkbox, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 3, 1, 1, 1)
        self.detectobjects_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.detectobjects_label.setFont(font)
        self.detectobjects_label.setAlignment(QtCore.Qt.AlignCenter)
        self.detectobjects_label.setObjectName("detectobjects_label")
        self.gridLayout_5.addWidget(self.detectobjects_label, 2, 0, 1, 1)
        self.graphicsdisplay_image = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsdisplay_image.setEnabled(True)
        self.graphicsdisplay_image.setMinimumSize(QtCore.QSize(900, 400))
        self.graphicsdisplay_image.setMaximumSize(QtCore.QSize(1000, 400))
        self.graphicsdisplay_image.setInteractive(True)
        self.graphicsdisplay_image.setObjectName("graphicsdisplay_image")
        self.gridLayout_5.addWidget(self.graphicsdisplay_image, 5, 0, 1, 2)
        self.import_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.import_label.setFont(font)
        self.import_label.setAlignment(QtCore.Qt.AlignCenter)
        self.import_label.setObjectName("import_label")
        self.gridLayout_5.addWidget(self.import_label, 0, 0, 1, 1)
        self.outputterminal_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.outputterminal_label.setFont(font)
        self.outputterminal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.outputterminal_label.setObjectName("outputterminal_label")
        self.gridLayout_5.addWidget(self.outputterminal_label, 6, 0, 1, 2)
        self.information_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.information_label.setFont(font)
        self.information_label.setAlignment(QtCore.Qt.AlignCenter)
        self.information_label.setObjectName("information_label")
        self.gridLayout_5.addWidget(self.information_label, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.help_button = QtWidgets.QPushButton(self.centralwidget)
        self.help_button.setObjectName("help_button")
        self.horizontalLayout.addWidget(self.help_button)
        self.faq_button = QtWidgets.QPushButton(self.centralwidget)
        self.faq_button.setObjectName("faq_button")
        self.horizontalLayout.addWidget(self.faq_button)
        self.gridLayout_5.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.browse_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_button.sizePolicy().hasHeightForWidth())
        self.browse_button.setSizePolicy(sizePolicy)
        self.browse_button.setObjectName("browse_button")
        self.gridLayout.addWidget(self.browse_button, 2, 0, 1, 1)
        self.imagesource_label = QtWidgets.QLabel(self.centralwidget)
        self.imagesource_label.setAlignment(QtCore.Qt.AlignCenter)
        self.imagesource_label.setObjectName("imagesource_label")
        self.gridLayout.addWidget(self.imagesource_label, 0, 0, 1, 1)
        self.file_label = QtWidgets.QLineEdit(self.centralwidget)
        self.file_label.setInputMask("")
        self.file_label.setObjectName("file_label")
        self.gridLayout.addWidget(self.file_label, 1, 0, 1, 1)
        self.algo_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.algo_dropdown.setObjectName("algo_dropdown")
        self.algo_dropdown.addItem("")
        self.algo_dropdown.addItem("")
        self.algo_dropdown.addItem("")
        self.gridLayout.addWidget(self.algo_dropdown, 2, 1, 1, 1)
        self.algo_label = QtWidgets.QLabel(self.centralwidget)
        self.algo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.algo_label.setObjectName("algo_label")
        self.gridLayout.addWidget(self.algo_label, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lane_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.lane_checkbox.setObjectName("lane_checkbox")
        self.gridLayout_2.addWidget(self.lane_checkbox, 2, 2, 1, 1)
        self.truck_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.truck_checkbox.setTabletTracking(True)
        self.truck_checkbox.setAutoFillBackground(False)
        self.truck_checkbox.setObjectName("truck_checkbox")
        self.gridLayout_2.addWidget(self.truck_checkbox, 0, 0, 1, 1)
        self.bus_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.bus_checkbox.setObjectName("bus_checkbox")
        self.gridLayout_2.addWidget(self.bus_checkbox, 1, 0, 1, 1)
        self.trafficlight_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.trafficlight_checkbox.setObjectName("trafficlight_checkbox")
        self.gridLayout_2.addWidget(self.trafficlight_checkbox, 2, 1, 1, 1)
        self.container_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.container_checkbox.setObjectName("container_checkbox")
        self.gridLayout_2.addWidget(self.container_checkbox, 0, 1, 1, 1)
        self.primemover_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.primemover_checkbox.setObjectName("primemover_checkbox")
        self.gridLayout_2.addWidget(self.primemover_checkbox, 2, 0, 1, 1)
        self.van_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.van_checkbox.setObjectName("van_checkbox")
        self.gridLayout_2.addWidget(self.van_checkbox, 1, 2, 1, 1)
        self.trailer_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.trailer_checkbox.setObjectName("trailer_checkbox")
        self.gridLayout_2.addWidget(self.trailer_checkbox, 1, 1, 1, 1)
        self.human_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.human_checkbox.setObjectName("human_checkbox")
        self.gridLayout_2.addWidget(self.human_checkbox, 0, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 3, 0, 1, 1)
        self.graphicdisplay_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.graphicdisplay_label.setFont(font)
        self.graphicdisplay_label.setAlignment(QtCore.Qt.AlignCenter)
        self.graphicdisplay_label.setObjectName("graphicdisplay_label")
        self.gridLayout_5.addWidget(self.graphicdisplay_label, 4, 0, 1, 2)
        self.outputterminal_textedit = QtWidgets.QTextEdit(self.centralwidget)
        self.outputterminal_textedit.setMinimumSize(QtCore.QSize(980, 100))
        self.outputterminal_textedit.setMaximumSize(QtCore.QSize(1000, 150))
        self.outputterminal_textedit.setObjectName("outputterminal_textedit")
        self.gridLayout_5.addWidget(self.outputterminal_textedit, 7, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.config_label.setText(_translate("MainWindow", "Configurations"))
        self.outputformat_dropdown.setItemText(0, _translate("MainWindow", "xml"))
        self.outputformat_dropdown.setItemText(1, _translate("MainWindow", "csv"))
        self.outputformat_dropdown.setItemText(2, _translate("MainWindow", "txt"))
        self.framrate_label.setText(_translate("MainWindow", "Playback Frame Rate "))
        self.outputformat_label.setText(_translate("MainWindow", "Output Format"))
        self.play_button.setText(_translate("MainWindow", "Play"))
        self.save_button.setText(_translate("MainWindow", "Save As"))
        self.framerate_dropdown.setItemText(0, _translate("MainWindow", "1"))
        self.framerate_dropdown.setItemText(1, _translate("MainWindow", "10"))
        self.framerate_dropdown.setItemText(2, _translate("MainWindow", "20"))
        self.framerate_dropdown.setItemText(3, _translate("MainWindow", "30"))
        self.framerate_dropdown.setItemText(4, _translate("MainWindow", "40"))
        self.displayannotation_checkbox.setText(_translate("MainWindow", "Display Annotation"))
        self.detectobjects_label.setText(_translate("MainWindow", "Detect Objects"))
        self.import_label.setText(_translate("MainWindow", "Import"))
        self.outputterminal_label.setText(_translate("MainWindow", "Output Terminal"))
        self.information_label.setText(_translate("MainWindow", "Information"))
        self.help_button.setText(_translate("MainWindow", "Help"))
        self.faq_button.setText(_translate("MainWindow", "FAQ"))
        self.browse_button.setText(_translate("MainWindow", "Browse"))
        self.imagesource_label.setText(_translate("MainWindow", "Image Source"))
        self.algo_dropdown.setItemText(0, _translate("MainWindow", "ML1"))
        self.algo_dropdown.setItemText(1, _translate("MainWindow", "ML2"))
        self.algo_dropdown.setItemText(2, _translate("MainWindow", "ML3"))
        self.algo_label.setText(_translate("MainWindow", "Algorithm"))
        self.lane_checkbox.setText(_translate("MainWindow", "Lane"))
        self.truck_checkbox.setText(_translate("MainWindow", "Truck"))
        self.bus_checkbox.setText(_translate("MainWindow", "Bus"))
        self.trafficlight_checkbox.setText(_translate("MainWindow", "Traffic Light"))
        self.container_checkbox.setText(_translate("MainWindow", "Container"))
        self.primemover_checkbox.setText(_translate("MainWindow", "Prime Mover"))
        self.van_checkbox.setText(_translate("MainWindow", "Van"))
        self.trailer_checkbox.setText(_translate("MainWindow", "Trailer"))
        self.human_checkbox.setText(_translate("MainWindow", "Human"))
        self.graphicdisplay_label.setText(_translate("MainWindow", "Graphics Display"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

